document.getElementById("ggl").addEventListener("click",function(){
    window.location="https://www.google.com";
    window.focus();
});
document.getElementById("fb").addEventListener("click",function(){
    window.location="https://www.facebook.com";
    window.focus();
});
document.getElementById("twt").addEventListener("click",function(){
    window.location="https://www.twitter.com";
    window.focus();
});